workspace:
  base: /drone/src
  path: github.com/dellintosh/golang-monorepo

pipeline:
  build:
    image: alpine:latest
    commands:
      - apk add --update --no-cache bash curl
      - pwd
      - ls -la
      - bash ./build.sh
