workspace:
  base: /drone/src
  path: github.com/dellintosh/golang-monorepo

pipeline:
  build:
    environment:
      - COMPARE_URL=something
    image: golang:1.11.2
    commands:
      - env
      - pwd
      - ls -la
      - bash ./build.sh
