workspace:
  base: /drone/src
  path: github.com/dellintosh/golang-monorepo

pipeline:
  build:
    image: alpine:latest
    commands:
      - pwd
      - ls -la
      - chmod +x ./build.sh
      - ./build.sh
