workspace:
  base: /drone/src
  path: github.com/dellintosh/golang-monorepo

pipeline:
  build:
    environment:
      - COMPARATIVE_URL=${DRONE_REPO_LINK}/compare/${DRONE_PREV_COMMIT_SHA}...${DRONE_COMMIT_SHA}
    image: golang:1.11.2
    commands:
      - export CIRCLE_COMPARE_URL=${DRONE_REPO_LINK}/compare/${DRONE_PREV_COMMIT_SHA}...${DRONE_COMMIT_SHA}
      - env
      - pwd
      - ls -la
      - bash ./build.sh
