workspace:
  base: /drone/src
  path: github.com/dellintosh/golang-monorepo

pipeline:
  build:
    environment:
      - CIRCLE_COMPARE_URL=${CI_REPO_LINK}/compare/${CI_PREV_COMMIT_SHA:0:8}...${CI_COMMIT_SHA:0:8}  # TODO: Make this generic
      - CIRCLE_SHA1=${CI_COMMIT_SHA:0:8}
    image: docker:18.09-git
    commands:
      - apk add --update --no-cache bash curl coreutils cmake
      - bash ./build.sh
